version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
